title: "Gadvala Aakash Kumar"
logo: assets/img/logo.jpeg
description: "Hi, I'm Aakash Kumar, a passionate Computer Science Engineering student currently pursuing my B.Tech at Global Institute of Engineering and Technology. I am interested in software development, machine learning, and emerging technologies. I enjoy building innovative projects, exploring new tools, and continuously improving my technical skills through practical learning and real-world applications. I'm particularly interested in the field of Data Science. I have good academic track record with a CGPA: 8.7."

# Social links
linkedin_username: aakash-kumar-gadvala-190172325
github_username: Gadvala

theme: jekyll-theme-minimal

# Optional: Add these if you want better formatting
markdown: kramdown
plugins:
  - jekyll-seo-tag
