title: Aakash Kumar Gadvala
logo: 
description:
<br>  
  Hi, I’m Aakash Kumar, a passionate Computer Science Engineering student currently pursuing my B.Tech at Global Institute of Engineering and Technology. I am interested in software development, machine learning, and emerging technologies. I enjoy building innovative projects, exploring new tools, and continuously improving my technical skills through practical learning and real-world applications.
  Im particularly intrested in the field of Data Science,I have good academic track record with a CGPA-8.7.
  <br>
<p align="center">
  <a href="C:\Users\plaov\OneDrive\Resume (3).pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/aakash-kumar-gadvala-190172325?utm_source=share_via&utm_content=profile&utm_medium=member_android">LinkedIn</a> |
  <a href="https://github.com/Gadvala>GitHub</a>
  
  
  </p>

theme: jekyll-theme-minimal
