title: <p align="center"> Gadvala Aakash Kumar </p>
logo: /assets/img/logo.jpeg

description:
  <p align="center">
  <a href="C:\Users\plaov\OneDrive\Resume (3).pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/aakash-kumar-gadvala-190172325">LinkedIn</a> |
  <a href="https://github.com/Gadvala">GitHub</a>
  
  <br>   
  I am Aakash Kumar Gadvala, a highly driven third-year B.Tech student pursuing Computer Science and Engineering (CSE) at Global Institute of Engineering and Technology. 
  I possess a solid academic background and a deep passion for leveraging technology to solve real-world problems.
  
  <br>
  </p>



theme: jekyll-theme-minimal
